import type { Metadata } from "next";

import { LegalPage, type LegalSection } from "@/components/legal/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How VaultDrop collects, uses, stores, and protects account, vault, and access data.",
};

const sections: LegalSection[] = [
  {
    id: "scope",
    title: "Scope",
    content: (
      <>
        <p>
          This Privacy Policy explains how VaultDrop handles information when
          you sign in, create or receive a vault, connect a wallet, or otherwise
          use the service.
        </p>
        <p>
          VaultDrop is an experimental encrypted file-sharing application. This
          policy applies to the VaultDrop website and application, but not to
          third-party services that have their own privacy policies.
        </p>
      </>
    ),
  },
  {
    id: "information-collected",
    title: "Information We Collect",
    content: (
      <>
        <p>Depending on how you use VaultDrop, we may process:</p>
        <ul>
          <li>
            <strong>Google account data:</strong> your Google user identifier,
            name, email address, and profile image when provided through Google
            sign-in.
          </li>
          <li>
            <strong>Account and session data:</strong> identifiers and essential
            authentication cookies managed through Supabase Auth.
          </li>
          <li>
            <strong>Vault data:</strong> vault names, file names, file sizes,
            MIME types, access conditions, timestamps, network selection, and
            encrypted file contents.
          </li>
          <li>
            <strong>Access activity:</strong> seal, view, unlock, denial,
            download, and revocation events associated with a vault.
          </li>
          <li>
            <strong>Wallet information:</strong> public wallet addresses and
            signed proofs when you choose to use wallet, token, or NFT access
            conditions.
          </li>
          <li>
            <strong>Technical data:</strong> request, error, security, and
            deployment logs generated by VaultDrop and its infrastructure
            providers.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "encrypted-files",
    title: "Encrypted Files and Keys",
    content: (
      <>
        <p>
          VaultDrop is designed to encrypt file contents in the sender&apos;s
          browser before upload. The service stores encrypted file contents
          rather than the original plaintext file.
        </p>
        <p>
          Content-encryption keys are wrapped to the configured enclave and
          released only through the vault&apos;s access-policy flow. Vault
          metadata, file names, conditions, and activity records are not
          necessarily encrypted in the same way as file contents.
        </p>
      </>
    ),
  },
  {
    id: "use",
    title: "How We Use Information",
    content: (
      <ul>
        <li>Authenticate users and maintain secure sessions.</li>
        <li>Associate vaults and sender controls with their owners.</li>
        <li>Create, store, share, unlock, audit, and revoke vaults.</li>
        <li>Evaluate access conditions and generate attestation records.</li>
        <li>Detect abuse, troubleshoot failures, and protect the service.</li>
        <li>Comply with applicable legal obligations.</li>
      </ul>
    ),
  },
  {
    id: "sharing",
    title: "Service Providers and Public Networks",
    content: (
      <>
        <p>
          VaultDrop relies on service providers including Google for sign-in,
          Supabase for authentication and database services, Vercel for hosting,
          and Flare network infrastructure for supported blockchain checks.
          These providers process data under their own terms and privacy
          policies.
        </p>
        <p>
          Wallet addresses and blockchain activity are public by nature. When
          you use an on-chain condition, related address and network information
          may be visible through public blockchain infrastructure.
        </p>
        <p>
          We do not sell Google account data or use it for advertising.
        </p>
      </>
    ),
  },
  {
    id: "cookies",
    title: "Cookies",
    content: (
      <p>
        VaultDrop uses essential cookies to maintain authentication and protect
        account sessions. VaultDrop does not currently use advertising cookies
        or cross-site behavioral advertising trackers.
      </p>
    ),
  },
  {
    id: "retention",
    title: "Retention and Deletion",
    content: (
      <>
        <p>
          Account, vault, encrypted-file, and audit data may be retained while
          needed to operate the service, maintain security records, resolve
          disputes, or meet legal obligations.
        </p>
        <p>
          Revoking a vault destroys its stored ciphertext in the current
          VaultDrop implementation. Some metadata, audit records, logs, or
          infrastructure backups may remain for a limited period.
        </p>
        <p>
          You may request account or personal-data deletion through the contact
          method below. We may need to verify your identity before completing a
          request.
        </p>
      </>
    ),
  },
  {
    id: "security",
    title: "Security",
    content: (
      <p>
        We use technical and organizational safeguards intended to protect
        information, including encrypted transport, authenticated sender
        controls, client-side file encryption, and access-policy enforcement.
        No online service can guarantee absolute security or uninterrupted
        availability.
      </p>
    ),
  },
  {
    id: "children",
    title: "Children",
    content: (
      <p>
        VaultDrop is not directed to children under 13, and we do not knowingly
        collect personal information from children under 13. If you believe a
        child has provided personal information, contact the operator so it can
        be reviewed and removed where appropriate.
      </p>
    ),
  },
  {
    id: "changes",
    title: "Changes to This Policy",
    content: (
      <p>
        We may update this policy as VaultDrop, its providers, or applicable
        requirements change. The date at the top of this page identifies the
        latest published version.
      </p>
    ),
  },
  {
    id: "contact",
    title: "Contact",
    content: (
      <p>
        For privacy questions or deletion requests, contact the VaultDrop
        operator through the{" "}
        <a
          href="https://github.com/Derojuu/VaultDrop"
          target="_blank"
          rel="noreferrer"
        >
          project repository
        </a>
        . Do not include passwords, private keys, passphrases, or confidential
        file contents in a public issue.
      </p>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Privacy"
      title="Privacy Policy"
      summary="This policy explains what information VaultDrop processes, why it is needed, and how encrypted files, Google account data, wallet proofs, and activity records are handled."
      sections={sections}
    />
  );
}
